server:
  port: 7070
  servlet:
    context-path: /
spring:
  application:
    name: pay-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/az_shop
    username: root
    password: root
  redis:
    database: 0
    password:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 200
        pool.max-wait: -1
        max-idle: 10
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  auto-dialect: mysql
  params: countSql
  reasonable: true
  support-methods-arguments: true
#\u6CE8\u518C\u5230eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

