
#\u7AEF\u53E3\u53F7
server:
  port: 10010
  servlet:
    context-path: /
#\u5E94\u7528\u540D\u79F0
spring:
  application:
    name: api-gateway
#eureka\u6CE8\u518C\u4E2D\u5FC3\u914D\u7F6E
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api
  retryable: true
  routes:
    item-service: /item/**
    sso-service: /sso/**
    pay-service: /pay/**

#\u8D1F\u8F7D\u914D\u7F6E
ribbon:
  ConnectTimeout: 250 # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4(ms)
  ReadTimeout: 2000 # \u901A\u4FE1\u8D85\u65F6\u65F6\u95F4(ms)
  OkToRetryOnAllOperations: true # \u662F\u5426\u5BF9\u6240\u6709\u64CD\u4F5C\u91CD\u8BD5
  MaxAutoRetriesNextServer: 1 # \u540C\u4E00\u670D\u52A1\u4E0D\u540C\u5B9E\u4F8B\u7684\u91CD\u8BD5\u6B21\u6570
  MaxAutoRetries: 1 # \u540C\u4E00\u5B9E\u4F8B\u7684\u91CD\u8BD5\u6B21\u6570

#\u7194\u65AD\u4FE1\u606F
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # \u7194\u65AD\u8D85\u65F6\u65F6\u957F\uFF1A10000ms

